INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_LIST_MINE', 'muestrame mis tareas');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_LIST_MINE', 'que pendientes tengo');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_LIST_MINE', 'lista mis tareas');

INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_LIST_BY_USER', 'que tareas tiene Juan');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_LIST_BY_USER', 'muestrame las tareas de ana@correo.com');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_LIST_BY_USER', 'pendientes asignados a Maria');

INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_CREATE', 'agrega una tarea para terminar el login');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_CREATE', 'crea tarea revisar permisos para sprint 2');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_CREATE', 'registra una nueva tarea de pruebas');

INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_DELETE', 'elimina la tarea 5');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_DELETE', 'borra task 12');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_DELETE', 'quiero quitar la tarea 8');

INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_UPDATE_STATUS', 'marca la tarea 5 como terminada');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_UPDATE_STATUS', 'pon la tarea 9 en progreso');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TASK_UPDATE_STATUS', 'cambia la tarea 3 a todo');

INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('SPRINT_LIST', 'que sprints estan activos');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('SPRINT_LIST', 'lista los sprints');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('SPRINT_LIST', 'muestrame los sprints cerrados');

INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('BUG_LIST', 'muestrame los bugs abiertos');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('BUG_LIST', 'que bugs hay');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('BUG_LIST', 'bugs de la tarea 7');

INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('ISSUE_LIST', 'muestrame los issues abiertos');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('ISSUE_LIST', 'issues del sprint 1');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('ISSUE_LIST', 'lista incidencias pendientes');

INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('KPI_SUMMARY', 'dame los KPIs');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('KPI_SUMMARY', 'como va el proyecto');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('KPI_SUMMARY', 'resumen de metricas del sprint');

INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TIME_ESTIMATED_VS_REAL', 'cuanto tiempo real llevamos contra el estimado');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TIME_ESTIMATED_VS_REAL', 'compara horas reales y estimadas');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('TIME_ESTIMATED_VS_REAL', 'tiempo estimado vs tiempo real del sprint');

INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('HELP', 'ayuda');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('HELP', 'comandos disponibles');
INSERT INTO VANTAGE.BOT_INTENT_EXAMPLES (INTENT_KEY, EXAMPLE_TEXT) VALUES ('HELP', 'que puedes hacer');

COMMIT;
