spring.datasource.url=jdbc:oracle:thin:@reacttodogxdmp_tp?TNS_ADMIN=C:/Users/pao_j/Documents/1_Principal/1_Escuela/Universidad/sextoSemestre/reto_Oracle/oci_devops_project/Wallet_reacttodogxdmp
spring.datasource.username=VANTAGE
spring.datasource.password=Littlecesar2005!

telegram.bot.token=8429232503:AAF7lfhxlRGpe9-Vll8j-G_3PIhkxbuV8Pk
telegram.bot.name=vantage_assistant_bot

deepseek.api.key=AIzaSyDGPU92CQFrAR0DFNA2Fd8Yo93DIHbf9OI




# configurations for local testing
spring.security.oauth2.client.registration.oci.client-id=e9416ef55b48402782d9c58608e9d106
spring.security.oauth2.client.registration.oci.client-secret=idcscs-9bef61f4-6c1e-4b2f-8115-e88f01c132e9
spring.security.oauth2.client.registration.oci.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.oci.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.oci.scope=openid,email,profile
spring.security.oauth2.client.registration.oci.client-name=OCI

#spring.security.oauth2.client.provider.oci.issuer-uri=https://idcs-879a0028c89849abaf750ac7bfa02c12.identity.oraclecloud.com:443


spring.security.oauth2.client.provider.oci.authorization-uri=https://idcs-879a0028c89849abaf750ac7bfa02c12.identity.oraclecloud.com/oauth2/v1/authorize
spring.security.oauth2.client.provider.oci.token-uri=https://idcs-879a0028c89849abaf750ac7bfa02c12.identity.oraclecloud.com/oauth2/v1/token
spring.security.oauth2.client.provider.oci.user-info-uri=https://idcs-879a0028c89849abaf750ac7bfa02c12.identity.oraclecloud.com/oauth2/v1/userinfo
spring.security.oauth2.client.provider.oci.jwk-set-uri=https://idcs-879a0028c89849abaf750ac7bfa02c12.identity.oraclecloud.com/admin/v1/SigningCert/jwk
spring.security.oauth2.client.provider.oci.user-name-attribute=sub