application-local.properties
spring.datasource.url=jdbc:oracle:thin:@reacttodogxdmp_tp?TNS_ADMIN=C:/Users/demmi/Documents/Coding/PROJECTS/oci_devops_project/Wallet_reacttodogxdmp
spring.datasource.username=VANTAGE
spring.datasource.password=Littlecesar2005!

telegram.bot.token=8767492402:AAG0CpVGDlVhZfiALsqQ5IUYxbXfBlCEm_U
telegram.bot.name=DemsElizabeth_bot

deepseek.api.key=AIzaSyDGPU92CQFrAR0DFNA2Fd8Yo93DIHbf9OI