applicaation-local.properties
spring.datasource.url=jdbc:oracle:thin:@reacttodogxdmp_tp?TNS_ADMIN=/home/oriana/Documents/GitHub/reto_oci_project/oci_devops_project/Wallet_reacttodogxdmp
spring.datasource.username=VANTAGE
spring.datasource.password=Littlecesar2005!

telegram.bot.token=8429232503:AAF7lfhxlRGpe9-Vll8j-G_3PIhkxbuV8Pk
telegram.bot.name=vantage_assistant_bot

deepseek.api.key=AIzaSyDGPU92CQFrAR0DFNA2Fd8Yo93DIHbf9OI