#PARA CORRER EN LOCAL, ACTIVAS EL PERFI LOCAL CON EL COMANDO: mvn spring-boot:run "-Dspring-boot.run.profiles=local"
spring.jpa.database-platform=org.hibernate.community.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:oracle.jdbc.OracleDriver}
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.sql-for-validate-connection=select * from dual
spring.datasource.oracleucp.connection-pool-name=connectionPoolName1
spring.datasource.oracleucp.initial-pool-size=15
spring.datasource.oracleucp.min-pool-size=10
spring.datasource.oracleucp.max-pool-size=30

logging.level.root=trace
logging.file.name=logs.log
logging.level.oracle.ucp=trace
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type=TRACE


deepseek.api.key=${DEEPSEEK_API_KEY:}
deepseek.api.url=${DEEPSEEK_API_URL:https://generativelanguage.googleapis.com/v1beta/openai/chat/completions}
deepseek.api.model=${DEEPSEEK_API_MODEL:gemini-2.5-flash}

telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
telegram.bot.name=${TELEGRAM_BOT_NAME:vantage_assistant_bot}


