
# create a application-local.properties file with the following content and fill in the values for your local environment. This file is ignored by git, so it won't be committed to the repository.
spring.datasource.url=jdbc:oracle:thin:@YOUR_DB_tp?TNS_ADMIN=C:/path/to/wallet
spring.datasource.username=YOUR_DB_USER
spring.datasource.password=YOUR_DB_PASSWORD

telegram.bot.token=YOUR_TELEGRAM_TOKEN
telegram.bot.name=YOUR_BOT_NAME

deepseek.api.key=YOUR_API_KEY


# configuration for local OAuth login testing
spring.security.oauth2.client.registration.oci.client-id=YOUR_OCI_CLIENT_ID
spring.security.oauth2.client.registration.oci.client-secret=YOUR_OCI_CLIENT_SECRET
spring.security.oauth2.client.registration.oci.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.oci.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.oci.scope=openid,email,profile
spring.security.oauth2.client.registration.oci.client-name=OCI

spring.security.oauth2.client.provider.oci.issuer-uri=YOUR_OCI_ISSUER_URI
